#!/bin/sh
## Used by jail-create, this script is run within the jail after it
## has been started. Run after jail.preinit and before jail.postinit.
## The default/jail.init is run for all new jails, and before any
## type-specific jail.init script is run.
## Available environmental vars: JAIL_NAME, JAIL_IP, JAIL_TYPE, JAIL_USER, JAIL_CONF_DIR

pkg install --yes node npm

npm install forever -g
