#!/bin/sh -e
## Create an empty jail and set its environment.
## This script looks for the file hooks: preconf, conf, and postconf,located within
## the jail type directory.
## Preconf and postconf are run on the host system, conf is run within the jail itself.

#shoud be something like /usr/local/opt/serverconf
APP_ROOT="$(cd $(dirname $(readlink -f $0))/../../../..; pwd)"
#add current user to jail by default (even if sudo'd)
JAIL_USER="$(who -m | cut -d ' ' -f1)"

print_help () {
  echo "Usage: $(basename $0) [options] -i=ipaddr" >&2;
  echo " -i=ipaddr  Address to bind jail" >&2;
  echo "Options:" >&2;
  echo " -n=name    Name of jail" >&2;
  echo " -t=type    Jail type (see $APP_ROOT/jails)" >&2;
  echo " -u=user    Add user to jail [default is current user]" >&2;
  echo " -h         Print this help message" >&2;
}

## Parse options

while getopts "n:i:t:u:h" opt; do
  case $opt in
    n) JAIL_NAME="$OPTARG";;
    i) JAIL_IP="$OPTARG";;
    t) JAIL_TYPE="$OPTARG";;
    u) JAIL_USER="$OPTARG";;
    h) print_help; exit 0;;
    \?) print_help; exit 1;;
  esac
done

if [ $(id -u) != 0 ]; then
  echo "$(basename $0): This script must be run as root." 1>&2
  exit 1
fi

if [ -z "$JAIL_TYPE" ]; then JAIL_TYPE='default'; fi

if [ ! -d "$APP_ROOT/jails/$JAIL_TYPE" ]; then
  echo "$(basename $0): Jail type '$JAIL_TYPE' doesn't exist, aborting." >&2
  exit 1
fi

if [ -z "$JAIL_IP" ]; then
  print_help
  exit 1
elif jls -v | grep "$JAIL_IP" > /dev/null; then
  echo -n "Address $JAIL_IP already used, you may experience network problems." 1>&2
  read -p " Continue? (y/n) " reply
  if [ "$reply" != 'y' -a "$reply" != 'yes' ]; then
    exit 0
  fi
fi

#if no id given, use typeN
if [ -z "$JAIL_NAME" ]; then
  #get the last jid (jid is incremented on start/restart)
  jid=$(jls | tail -1 | awk '{print $1}')
  if [ $jid == 'JID' ]; then
    jid=0
  else
    #1 plus the last jid at least guarantees a unique name, not descriptive though
    jid=$((jid+1))
  fi
  JAIL_NAME="${JAIL_TYPE}$jid"
fi

#ezjail converts all non-alphanums to underscore, we should too
JAIL_NAME=$(echo -n "$JAIL_NAME" | tr -c '[[:alnum:]]' '_')

if [ -e "/usr/local/etc/ezjail/$JAIL_NAME" ]; then
  echo "$(basename $0): Jail '$JAIL_NAME' already exists, use a different name." >&2;
  exit 1
fi


## Helper functions

cp_conf () {
  local srcpath="$1" destdir="$2" replacevars="$3" ignorevars="$4"
  env REPLACE_VARS="$replacevars JAIL_NAME JAIL_IP JAIL_TYPE JAIL_USER JAIL_CONF_DIR" \
      NO_REPLACE_VARS="$ignorevars" \
      JAIL_NAME="$JAIL_NAME" \
      JAIL_IP="$JAIL_IP" \
      JAIL_TYPE="$JAIL_TYPE" \
      JAIL_USER="$JAIL_USER" \
      JAIL_CONF_DIR="$APP_ROOT/jails/$jailtype" \
      sh -e "$APP_ROOT/src/cp-conf.sh" "$srcpath" "$destdir"
}

jail_hook () {
  local hookname="$1" hookenv="$2"
  env JAIL_IP="$JAIL_IP" \
      JAIL_USER="$JAIL_USER" \
      sh -e "$APP_ROOT/src/jail-hook.sh" "$JAIL_NAME" "$hookname" "$hookenv"
}


## Create

if ! ezjail-admin create "$JAIL_NAME" "$JAIL_IP"; then
  echo "$(basename $0): Unable to create jail, aborting." >&2;
  exit 1
fi

# add config vars that can be reached within the jail
jailconf="/usr/jails/$JAIL_NAME/etc/serverconf"

if [ ! -f "$jailconf" ]; then touch "$jailconf"; fi

if ! sh -e "$APP_ROOT/src/confkey.sh" -f "$jailconf" -k "jailtype" -v "$JAIL_TYPE"; then
  echo "$(basename $0): Error setting jail config file, exiting." >&2
  exit 1
fi

## Preconf
## Modify config dir before copying into jail.

jail_hook 'preconf' 'host'

# Copy jail config to host

if [ -d "$APP_ROOT/jails/default/host" ]; then
  cp_conf "$APP_ROOT/jails/default/host" /
fi
if [ "$JAIL_TYPE" != "default" -a -d "$APP_ROOT/jails/$JAIL_TYPE/host" ]; then
  cp_conf "$APP_ROOT/jails/$JAIL_TYPE/host" /
fi

## Conf
## Start jail and run scripts within it.

echo "Configuring jail ..."

if ! ezjail-admin start "$JAIL_NAME"; then
  echo "$(basename $0): Unable to start jail, aborting." >&2;
  exit 1
fi

# Copy jail config to jail after conf has chance to install packages

if [ -d "$APP_ROOT/jails/default/jail" ]; then
  cp_conf "$APP_ROOT/jails/default/jail" "/usr/jails/$JAIL_NAME"
fi
if [ "$JAIL_TYPE" != "default" -a -d "$APP_ROOT/jails/$JAIL_TYPE/jail" ]; then
  cp_conf "$APP_ROOT/jails/$JAIL_TYPE/jail" "/usr/jails/$JAIL_NAME"
fi

jail_hook 'conf' 'jail'

## Postconf

jail_hook 'postconf' 'host'

echo "Restarting jail ..."

if ! ezjail-admin restart "$JAIL_NAME"; then
  echo "$(basename $0): Unable to restart jail, aborting." >&2;
  exit 1
fi

echo "$JAIL_NAME jail running on $JAIL_IP"
