#!/bin/sh -e

JAIL_TYPE_DEFAULT='default'

print_help () {
  echo "Usage: $(basename $0) [options] jailname" >&2;
  echo "Options:" >&2;
  echo " -X  Don't run the '$JAIL_TYPE_DEFAULT' delete hooks" >&2;
  echo " -h  Print this help message" >&2;
}

while getopts "Xh" opt; do
  case $opt in
    X) NO_DEFAULT_HOOK=1;;
    h) print_help; exit 0;;
    \?) print_help; exit 1;;
  esac
done

##
## GET PARAMS
##

for lastarg; do true; done
JAIL_NAME="$lastarg"

if [ -z "$JAIL_NAME" ]; then print_help; exit 1; fi

if [ ! -e "/usr/local/etc/ezjail/$JAIL_NAME" -o ! -e "/usr/jails/$JAIL_NAME" ]; then
  echo "$(basename $0): Jail '$JAIL_NAME' doesn't exist, exiting." >&2;
  exit 1
fi

APP_ROOT="$(cd $(dirname $(readlink -f $0))/../../../..; pwd)"

##
## RUN HOOKS, DELETE JAIL
##

jail_hook () {
  local hookname="$1" hookenv="$2"
  env NO_DEFAULT_HOOK="$NO_DEFAULT_HOOK" \
      sh -e "$APP_ROOT/src/jail-hook.sh" "$JAIL_NAME" "$hookname" "$hookenv"
}


jail_hook 'predelete' 'host'

jail_hook 'delete' 'jail'

# -w wipe directory, -f stop jail before deletion
if ! ezjail-admin delete -w -f "$JAIL_NAME"; then
  echo "$(basename $0): Unable to delete jail, aborting." >&2;
  exit 1
fi

jail_hook 'postdelete' 'host'

echo "Jail '$JAIL_NAME' deleted."
