#!/bin/sh
## Used by jail-create, this script is run within the jail after it
## has been started. Run after jail.preinit and before jail.postinit.
## The default/jail.init is run for all new jails, and before any
## type-specific jail.init script is run.
## Available environmental vars: JAIL_ID, JAIL_IP, JAIL_TYPE, JAIL_USER, JAIL_CONF_DIR

if ! pkg -N  >/dev/null 2>&1; then
  env ASSUME_ALWAYS_YES=YES pkg bootstrap
fi

pkg update
pkg install --yes sudo

# set root environment

cp /usr/share/skel/dot.profile "$HOME/.profile"
chsh -s /bin/sh

# add user if they don't already exist

if [ -n "$JAIL_USER" ]; then
  if ! id "$JAIL_USER" >/dev/null 2>&1; then
    pw useradd -n "$JAIL_USER" -m -s /bin/sh
  fi
fi
