#!/bin/sh
## Used by jail-create, this script is run on the host system after the
## jail has been created and started. Ran after jail/init.
## The default/postinit file is run for all new jails, and before any
## type-specific jail/postinit script is run.
## Available environmental vars: JAIL_ID, JAIL_IP, JAIL_TYPE, JAIL_USER, JAIL_CONF_DIR
