#!/bin/sh
## Used by jailconf, this script is run on the host system after the
## jail has been created and started. It's run after {jailtype}/init.
## The default/postinit file is run for all new jails, and before any
## type-specific {jailtype}/init script is run.
## Available environmental vars: JAIL_NAME, JAIL_IP, JAIL_TYPE, JAIL_USER, JAIL_CONF_DIR
