#!/bin/sh
## Used by jail-create, this script is run on the host system before the
## jail has been created and started. Ran before jail/init.
## The default/preinit file is run for all new jails, and before any
## type-specific jail/preinit script is run.
## Available environmental vars: JAIL_ID, JAIL_IP, JAIL_TYPE, JAIL_USER, JAIL_CONF_DIR

# use host's networking
cp /etc/hosts "/usr/jails/$JAIL_ID/etc/"
cp /etc/resolv.conf "/usr/jails/$JAIL_ID/etc/"

#set jail to host time
cp /etc/localtime "/usr/jails/$JAIL_ID/etc/"

# copy to the base jail so we can overwrite with our jail-specific config
cp -R /usr/share/skel/*  /usr/jails/basejail/usr/share/skel/
